#!/usr/bin/env python

# vim: sw=4:ts=4:sts=4:fdm=indent:fdl=0:
# -*- coding: UTF8 -*-
#
# Test the player object.
# Copyright (C) 2012-2013 Josiah Gordon <josiahg@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


"""Print out any info found in audio files."""

from musio.io_util import open_file

if __name__ == "__main__":
    import pathlib
    from sys import argv

    if argv[1:]:
        for filename in argv[1:]:
            if pathlib.Path(filename).is_file():
                try:
                    with open_file(filename) as tmp_file:
                        print(tmp_file)
                except Exception:
                    print(filename)
